# version: "3.9"
# services:
#   app:
#     build: ./infra/php
#     volumes:
#       - ./backend:/work

# web: nginx:1.20-alpine
# ports:
#   - 8080:80
# volume:
#   - ./backend:/work
#   - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
# working_dir: /work

version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  # 追記
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
